version: '3'

services:
  express-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3001:3001" # host port : container port
    volumes:
      - .:/app # mount, eli yhdistet채채n t채m채 kansio containerin kansioon /app
    environment:
      - NODE_ENV=development